# No downloads. Prefer installed Arrow CMake packages; alternatively use the
# headers and shared libraries shipped in a local PyArrow wheel.
set(VQE_ARROW_ROOT "" CACHE PATH "Directory containing Arrow include/ and shared libraries (e.g. pyarrow)")
if(VQE_ARROW_ROOT)
  find_path(VQE_ARROW_INCLUDE arrow/api.h PATHS "${VQE_ARROW_ROOT}/include" NO_DEFAULT_PATH REQUIRED)
  foreach(component arrow parquet)
    file(GLOB candidates "${VQE_ARROW_ROOT}/lib${component}.*.dylib" "${VQE_ARROW_ROOT}/lib${component}.so.*")
    list(SORT candidates COMPARE NATURAL ORDER DESCENDING)
    if(NOT candidates)
      message(FATAL_ERROR "No ${component} shared library in VQE_ARROW_ROOT")
    endif()
    list(GET candidates 0 library)
    add_library(vqe_${component} SHARED IMPORTED)
    set_target_properties(vqe_${component} PROPERTIES IMPORTED_LOCATION "${library}" INTERFACE_INCLUDE_DIRECTORIES "${VQE_ARROW_INCLUDE}")
  endforeach()
  target_link_libraries(vqe PUBLIC vqe_arrow vqe_parquet)
else()
  find_package(Arrow 21 CONFIG REQUIRED)
  find_package(Parquet 21 CONFIG REQUIRED)
  target_link_libraries(vqe PUBLIC Arrow::arrow_shared Parquet::parquet_shared)
endif()
